allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  maplibre-gl: true
  prisma: true
  unrs-resolver: true
  vue-demi: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
